name: nit_tools_flutter
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_hooks: ^0.20.1
  hooks_riverpod: ^2.4.10
  freezed_annotation: ^2.4.4
  riverpod_annotation: ^2.3.5
  scrollview_observer: ^1.26.1
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  collection: ^1.18.0
  flutter_multi_formatter: ^2.13.0

  serverpod_client: 2.1.5
  serverpod_auth_client: 2.1.5
  serverpod_auth_shared_flutter: 2.1.5

  dartway_flutter:
    git: 
      url: https://github.com/dartway/dartway_flutter.git
      ref: master

  nit_tools_client:
    git:
      url: https://github.com/novikov-it/nit_tools.git
      path: nit_tools_client
      ref: master

  # chat
  wechat_assets_picker: ^9.5.0
  audio_waveforms: ^1.3.0
  swipe_to: ^1.0.6
  cached_network_image: ^3.4.1
  gap: ^3.0.1
  carousel_slider: ^5.0.0

  intl: ^0.19.0
  path_provider: ^2.1.5
  path: ^1.9.0
  image_picker: ^1.1.2
  heif_converter: ^1.0.1
  image: ^4.5.4

  go_router: ^14.0.0
  http: ^1.6.0
  http_parser: ^4.1.2






dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

dependency_overrides:
  nit_tools_client:
    path: ../nit_tools_client
  serverpod_auth_client:
    # path: ../nit_serverpod/modules/serverpod_auth/serverpod_auth_client
    git:
      url: https://github.com/novikov-it/nit_serverpod.git
      path: modules/serverpod_auth/serverpod_auth_client

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
